name: Deploy GCP infrastructure

on: 
  workflow_dispatch:
    inputs:
      tfpath:
        description: 'TF File Path'     
        required: true
        default: 'terraform/'

env:
  TF_VAR_credentials_file: ${{ secrets.GCP_SA_KEY }}
  
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Terraform init
        run:
          terraform init
        working-directory: ${{ github.event.inputs.tfpath }}
      - name: Terraform validate
        run:
          terraform validate
        working-directory: ${{ github.event.inputs.tfpath }}
      - name: Terraform plan
        run:
          terraform plan --var="credentials_file=$TF_VAR_credentials_file"
        working-directory: ${{ github.event.inputs.tfpath }}
      - name: Terraform apply
        run:
          terraform apply  --auto-approve --var="credentials_file=$TF_VAR_credentials_file"
        working-directory: ${{ github.event.inputs.tfpath }}