name: TEST2


on: 
  push:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
        echo "Log level: ${{ github.on.push.inputs.logLevel }}"
        echo "Tags: ${{ github.on.push.inputs.tags }}" 
        echo "Log level: ${{ on.push.inputs.logLevel }}"
        echo "Tags: ${{ on.push.inputs.tags }}" 